{
 "title": "BitBackup!",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "# BitBackup!\n\nPrimer acercamiento para poder ver informacion de los backups \nde BitBucket.\n\nSeria piola poder ver la informacion de tareas anteriores\ny tambien los borrados por retencion."
   },
   "targets": [
    {
     "dataset": "ExampleDB",
     "rawSql": "Select FailedBackups from BackupTasks\r\nwhere TaskID in (\r\n  Select max(TaskID) from BackupTasks\r\n)"
    }
   ]
  },
  {
   "title": "Repositorios respaldados",
   "type": "table",
   "gridPos": { "h": 21, "w": 10, "x": 5, "y": 0 },
   "targets": [
    {
     "dataset": "ExampleDB",
     "rawSql": "Select RepoName from RepositoryBackups\r\nwhere Status = 'Success'\r\nand TaskID in (\r\n  Select max(TaskID) from BackupTasks\r\n)\r\norder by 1"
    }
   ]
  },
  {
   "title": "Repositorios fallidos",
   "type": "table",
   "gridPos": { "h": 21, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "dataset": "ExampleDB",
     "rawSql": "Select RepoName, ErrorMessage from RepositoryBackups\r\nwhere Status = 'Failed'\r\nand TaskID in (\r\n  Select max(TaskID) from BackupTasks\r\n)\r\norder by 1"
    }
   ]
  },
  {
   "title": "Ultimo backup",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "dataset": "ExampleDB",
     "rawSql": "Select EndTime from BackupTasks\r\nwhere TaskID in (\r\n  Select max(TaskID) from BackupTasks\r\n) "
    }
   ]
  },
  {
   "title": "Tiempo procesado de ultimo backup",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "dataset": "ExampleDB",
     "rawSql": "Select \r\n    CAST(DATEDIFF(SECOND, StartTime, EndTime) / 3600 as varchar) + ' horas, ' +\r\n    CAST((DATEDIFF(SECOND, StartTime, EndTime) % 3600) / 60 as varchar) + ' minutos, ' +\r\n    CAST(DATEDIFF(SECOND, StartTime, EndTime) % 60 as varchar) + ' segundos' AS TiempoTranscurrido\r\nfrom BackupTasks\r\nwhere TaskID in (\r\n  Select max(TaskID) from BackupTasks\r\n)"
    }
   ]
  },
  {
   "title": "Total de repositorios leidos",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "ExampleDB",
     "rawSql": "Select TotalRepos from BackupTasks\r\nwhere TaskID in (\r\n  Select max(TaskID) from BackupTasks\r\n)"
    }
   ]
  },
  {
   "title": "Total de repositorios respaldados",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 15 },
   "targets": [
    {
     "dataset": "ExampleDB",
     "rawSql": "Select SuccessfulBackups from BackupTasks\r\nwhere TaskID in (\r\n  Select max(TaskID) from BackupTasks\r\n)"
    }
   ]
  },
  {
   "title": "Total de repositorios fallidos",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "ExampleDB",
     "rawSql": "Select FailedBackups from BackupTasks\r\nwhere TaskID in (\r\n  Select max(TaskID) from BackupTasks\r\n)"
    }
   ]
  }
 ]
}